services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
